### ISSUE TITLE
krzywo na tel

### ISSUE THREAD

**Issue by Coreli0** [Wizzy-TV/HyenaCode#1]
![opera_VhO3fizMwV](https://github.com/Wizzy-TV/HyenaCode/assets/100584937/6297716c-4819-4900-a584-cb59bdba540d)

**Comment by Wizzy-TV** [comment]
Zdaje sobie z tego sprawę, jednak ten błąd ani nie przeszkadza w funkcjonowaniu edytora, ani nie szpeci (według mnie), więc nie mam na razie w planach, specjalnie dla takiego małego "błędu" modyfikować kodu, gdzie czas jaki w to włożę nie będzie wart takiej nieistotnej zmiany. Jednak gratulacje za spostrzegawczość :D
